FROM node:alpine

ENV http_proxy http://jm91722:JSM20190122;1@proxy.internal.epo.org:8080
ENV https_proxy http://jm91722:JSM20190122;1@proxy.internal.epo.org:8080

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]